### ISSUE TITLE
Working Install Instructions

### ISSUE THREAD

**Issue by jamesbraza** [google/yamlfmt#59]
Following the currently suggested install instructions: `go install github.com/google/yamlfmt/cmd/yamlfmt@latest`

```bash
> go install github.com/google/yamlfmt/cmd/yamlfmt@latest
go: downloading github.com/google/yamlfmt v0.5.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/RageCage64/multilinediff v0.2.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/bmatcuk/doublestar/v4 v4.2.0
go: downloading github.com/RageCage64/go-utf8-codepoint-converter v0.1.0
go: downloading github.com/google/go-cmp v0.5.9
> yamlfmt
zsh: command not found: yamlfmt
```

The request is to have working install instructions in the `README`.  Excited to start using `yamlfmt`!

**Comment by braydonk** [comment]
Thanks for making an issue! 
`go install` actually installs the binary to the `GOBIN` environment variable, which is by default `$HOME/go/bin`. If you add `$HOME/go/bin` to your path this should work. I forgot that this wasn't done by default. I'll adjust the install instructions to mention that.

**Comment by jamesbraza** [comment]
Yeah fwiw I added this to my `~/.zshrc`: `export PATH=$PATH:$(go env GOPATH)/bin`.

Thank you!

**Comment by braydonk** [comment]
Sorry I'd forgotten about this. In #73 I included a new line to suggest a DigitalOcean article that has a `go install` setup guide. Hopefully this should work!

**Comment by larmitage-bjss** [comment]
Hi, I'm not sure if the DigitalOcean page you've linked to has changed since you linked to it, but I find the install process at least as confusing as without it. The DO docs are also confusing though, I think you want to link [here](https://www.digitalocean.com/community/tutorial_series/how-to-install-and-set-up-a-local-programming-environment-for-go) for people to find the article for their own OS, but the one for mac at least implies that installing go using brew will set up the path for you which didn't work for me.

I think it would be clearer to just say that the `$GOPATH` directory needs adding to your path if you've not used Go before, and how you do that will be dependent on your OS and shell (maybe add the `~/.zshrc` example by @jamesbraza above which is also what I used: `export PATH=$PATH:$(go env GOPATH)/bin`)

Thanks!
