### ISSUE TITLE
Option to Specify Line Length

### ISSUE THREAD

**Issue by jamesbraza** [google/yamlfmt#60]
I use [`yamllint --strict`](https://github.com/adrienverge/yamllint) to check my YAML files, and it checks one's YAML fits into 80-chars.

It looks like `yamlfmt` is wrapping my lines to be longer than 80-chars.  Looking at the [Basic Formatter](https://github.com/google/yamlfmt/tree/main/formatters/basic), I don't see a config option to change this line wrap.

It would be nice to add `line_length` as a config option to the formatter.  Cheers!

**Comment by braydonk** [comment]
This is being tracked in #39. Unfortunately this one is going to be a lot harder to make happen because it can't be done in a context free way like some of the other requested features. It will have to wait until I have more control of the yaml parsing step, either through a hard fork of `yaml.v3` or a new yaml parser.

**Comment by jamesbraza** [comment]
Ha I see this is like a blatant dup issue (my bad).  Looking forward to this feature, so I can adopt!
